name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy azure-storage-blob pytest

      - name: Run unit tests
        run: pytest -q

      # Optional Docker build + push (only runs when DOCKERHUB_USERNAME & DOCKERHUB_TOKEN are set)
      - name: Build Docker image
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build -t diet-analysis:${{ github.sha }} .

      - name: Log in to Docker Hub (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push image to Docker Hub (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        run: |
          docker tag diet-analysis:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/diet-analysis:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diet-analysis:latest

      # Optional SSH deploy (only runs if SSH secrets present)
      - name: Optional remote deploy via SSH
        if: ${{ secrets.SSH_HOST && secrets.SSH_USER && secrets.SSH_PRIVATE_KEY }}
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/diet-analysis:latest
            docker rm -f diet-analysis || true
            docker run -d --name diet-analysis ${{ secrets.DOCKERHUB_USERNAME }}/diet-analysis:latest
